### ISSUE TITLE
OSError: Error no file named diffusion_pytorch_model.bin found

### ISSUE THREAD

**Issue by eagle-dai** [jeanne-wang/svd_keyframe_interpolation#1]
```
$ bash keyframe_interpolation.sh
example_001
C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
A matching Triton is not available, some optimizations will not be enabled
Traceback (most recent call last):
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\xformers\__init__.py", line 57, in _is_triton_available
    import triton  # noqa
ModuleNotFoundError: No module named 'triton'
C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\huggingface_hub\file_download.py:1150: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Loading pipeline components...: 100%|##########| 5/5 [00:00<00:00,  8.55it/s]
Traceback (most recent call last):
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\keyframe_interpolation.py", line 98, in <module>
    main(args)
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\keyframe_interpolation.py", line 28, in main
    finetuned_unet = UNetSpatioTemporalConditionModel.from_pretrained(
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\diffusers\models\modeling_utils.py", line 632, in from_pretrained
    model_file = _get_model_file(
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\Users\******\workspace\aigc\svd_keyframe_interpolation\venv\lib\site-packages\diffusers\utils\hub_utils.py", line 306, in _get_model_file
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory checkpoints/svd_reverse_motion_with_attnflip.

```

**Comment by zhou-linpeng** [comment]
you can modified
`finetuned_unet = UNetSpatioTemporalConditionModel.from_pretrained(
        args.checkpoint_dir,
        subfolder="unet",
        torch_dtype=torch.float16,
    ) 
`
to
`
finetuned_unet = UNetSpatioTemporalConditionModel.from_pretrained(
        args.checkpoint_dir,
        subfolder="unet",
        torch_dtype=torch.float16,
        use_safetensors=True
    ) 
`

**Comment by Huster-Hq** [comment]
> finetuned_unet = UNetSpatioTemporalConditionModel.from_pretrained( args.checkpoint_dir, subfolder="unet", torch_dtype=torch.float16, use_safetensors=True )

After modification, I still have errors.

`Error no file named diffusion_pytorch_model.safetensors found in directory checkpoints/svd_reverse_motion_with_attnflip.`

**Comment by XuandYu000** [comment]
> > finetuned_unet = UNetSpatioTemporalConditionModel.from_pretrained( args.checkpoint_dir, subfolder="unet", torch_dtype=torch.float16, use_safetensors=True )
> 
> After modification, I still have errors.
> 
> `Error no file named diffusion_pytorch_model.safetensors found in directory checkpoints/svd_reverse_motion_with_attnflip.`

Rename the checkpoint downloaded from the author's link to `diffusion_pytorch_model.safetensor`. Then put it in `checkpoints/svd_reverse_motion_with_attnflip/unet`.
