### ISSUE TITLE
inference error

### ISSUE THREAD

**Issue by Huster-Hq** [jeanne-wang/svd_keyframe_interpolation#12]
example_001
/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f57cb15dfa0>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57cb15dfa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 387, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f57cb15dfa0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: f6aa1fe1-eee2-4719-b479-910f4aad67f9)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1339, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1857, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keyframe_interpolation.py", line 98, in <module>
    main(args)
  File "keyframe_interpolation.py", line 16, in main
    noise_scheduler = EulerDiscreteScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 143, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-video-diffusion-img2vid-xt does not appear to have a file named scheduler_config.json.
example_001.gif
/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py:1142: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f9e6fc20f40>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e6fc20f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1746, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 387, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /stabilityai/stable-video-diffusion-img2vid-xt/resolve/main/scheduler/scheduler_config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9e6fc20f40>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 6f19e4f5-560c-4c73-8f73-4649c4216835)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 380, in load_config
    config_file = hf_hub_download(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1339, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1857, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "keyframe_interpolation.py", line 98, in <module>
    main(args)
  File "keyframe_interpolation.py", line 16, in main
    noise_scheduler = EulerDiscreteScheduler.from_pretrained(args.pretrained_model_name_or_path, subfolder="scheduler")
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/schedulers/scheduling_utils.py", line 143, in from_pretrained
    config, kwargs, commit_hash = cls.load_config(
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/huqiang/anaconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/configuration_utils.py", line 406, in load_config
    raise EnvironmentError(
OSError: stabilityai/stable-video-diffusion-img2vid-xt does not appear to have a file named scheduler_config.json.

**Comment by Yuhuoo** [comment]
I encountered the same problem, how did you solve it?

**Comment by Huster-Hq** [comment]
> I encountered the same problem, how did you solve it?

I haven't managed to run the inference code yet.

**Comment by alexlawford** [comment]
Hi, I have the same problem. Were you able to solve in the end @Huster-Hq or @Yuhuoo ?
