### ISSUE TITLE
size of result is 1024x576

### ISSUE THREAD

**Issue by Armin199608** [jeanne-wang/svd_keyframe_interpolation#13]
hello,Is this the only size available? Can it be changed? How to adjust? After set"width=720,height=1280" , the error message is as follows:
Traceback (most recent call last):
  File "keyframe_interpolation.py", line 112, in <module>
    main(args)
  File "keyframe_interpolation.py", line 78, in main
    frames = pipe(image1=frame1, image2=frame2, 
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/svd_keyframe_interpolation/custom_diffusers/pipelines/pipeline_frame_interpolation_with_noise_injection.py", line 529, in __call__
    noise_pred = self.multidiffusion_step(latents, t, 
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/code/svd_keyframe_interpolation/custom_diffusers/pipelines/pipeline_frame_interpolation_with_noise_injection.py", line 287, in multidiffusion_step
    noise_pred1 = self.ori_unet(
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/models/unets/unet_spatio_temporal_condition.py", line 463, in forward
    sample = upsample_block(
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/diffusers-0-27-0/lib/python3.8/site-packages/diffusers/models/unets/unet_3d_blocks.py", line 2361, in forward
    hidden_states = torch.cat([hidden_states, res_hidden_states], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.

**Comment by jeanne-wang** [comment]
Hi, Because of the UNet structure in Stable Video Diffusion, you have to make sure the size of the image is a multiple of 64.
